Fix Docker Hub publishing

diff --git a/.github/workflows/docker-image-release.yml b/.github/workflows/docker-image-release.yml
--- a/.github/workflows/docker-image-release.yml
+++ b/.github/workflows/docker-image-release.yml
@@ -13,12 +13,12 @@ env:
   # Define one of test report format: dart-json, dotnet-trx, flutter-json, java-junit, jest-junit, mocha-json
   TEST_REPORT_FORMAT: java-junit
   # Override path to GitHub Container Repository
-  GHCR_REPOSITORY: "${{ github.repository }}/typescript-service"
+  REGISTRY_GHCR_REPOSITORY_PATH: "${{ github.repository }}/typescript-service"
   # Set to "yes" to publish image into https://hub.docker.com
-  DOCKERHUB_PUBLISH: yes
+  PUBLISH_DOCKERHUB: yes
   # Override path to Docker Hub repository
-  #DOCKERHUB_REPOSITORY: "${{ github.repository }}"
-  DOCKERHUB_REPOSITORY: "theanurin/edgebus"
+  #REGISTRY_DOCKERHUB_REPOSITORY_PATH: "${{ github.repository }}"
+  REGISTRY_DOCKERHUB_REPOSITORY_PATH: "theanurin/edgebus"
 
 on:
   push:
@@ -117,7 +117,7 @@ jobs:
         echo "project_url=${BUILD_PROJECT_URL}" | tee -a "${GITHUB_OUTPUT}"
         echo "rc_version=${BUILD_RC_VERSION}" | tee -a "${GITHUB_OUTPUT}"
         echo "tag_version=${BUILD_TAG_VERSION}" | tee -a "${GITHUB_OUTPUT}"
-        case "${DOCKERHUB_PUBLISH}" in
+        case "${PUBLISH_DOCKERHUB}" in
           yes|YES)
             echo "dockerhub_publish=yes" | tee -a "${GITHUB_OUTPUT}"
             ;;
@@ -173,7 +173,7 @@ jobs:
           BUILD_VERSION_APPENDER=${{ needs.configure.outputs.build_version_appender }}
         platforms: ${{ join(fromJson(needs.configure.outputs.build_platforms), ',') }}
         push: true
-        tags: "ghcr.io/${{ env.GHCR_REPOSITORY }}${{ env.DOCKERFILE_NAME_SUFFIX }}:${{ github.ref_name }}.${{ github.sha }}"
+        tags: "ghcr.io/${{ env.REGISTRY_GHCR_REPOSITORY_PATH }}${{ env.DOCKERFILE_NAME_SUFFIX }}:${{ github.ref_name }}.${{ github.sha }}"
 
   docker-test:
     needs:
@@ -212,7 +212,7 @@ jobs:
       run: |
         docker build \
           --platform=${{ matrix.platform }} \
-          --build-arg TEST_IMAGE="ghcr.io/${{ env.GHCR_REPOSITORY }}${APP_DOCKER_IMAGE_SUFFIX}:${{ github.ref_name }}.${{ github.sha }}" \
+          --build-arg TEST_IMAGE="ghcr.io/${{ env.REGISTRY_GHCR_REPOSITORY_PATH }}${APP_DOCKER_IMAGE_SUFFIX}:${{ github.ref_name }}.${{ github.sha }}" \
           --build-arg BUILD_CONFIGURATION=release \
           --tag "${GEN_IMAGE_TAG}" \
           --file "${DOCKER_FILES_DIR}/${{ matrix.dockerfile }}" \
@@ -258,7 +258,7 @@ jobs:
     - name: Check conditions
       run: |
         if [ "${{ needs.configure.outputs.build_app_dockerfiles_count }}" != '1' ]; then
-          echo "Failure! This repository contains more that one application Dockerfile. The job available for repositories with one application Dockerfile only. To skip the job use 'DOCKERHUB_PUBLISH: false'" >&2
+          echo "Failure! This repository contains more that one application Dockerfile. The job available for repositories with one application Dockerfile only. To skip the job use 'PUBLISH_DOCKERHUB: false'" >&2
           exit 1
         fi
 
@@ -279,17 +279,17 @@ jobs:
     - name: Log in to the Docker Hub Registry
       uses: docker/login-action@v2
       with:
-        username: ${{ vars.DOCKERHUB_USERNAME }}
-        password: ${{ secrets.DOCKERHUB_TOKEN }}
+        username: ${{ vars.REGISTRY_DOCKERHUB_PUSH_USERNAME }}
+        password: ${{ secrets.REGISTRY_DOCKERHUB_PUSH_TOKEN }}
 
     - name: Tags and push
       run: |
         skopeo copy --all \
-          "docker://ghcr.io/${{ env.GHCR_REPOSITORY }}${DOCKERFILE_NAME_SUFFIX}:${{ github.ref_name }}.${{ github.sha }}" \
-          "docker://${DOCKERHUB_REPOSITORY}:${{ github.ref_name }}"
+          "docker://ghcr.io/${{ env.REGISTRY_GHCR_REPOSITORY_PATH }}${DOCKERFILE_NAME_SUFFIX}:${{ github.ref_name }}.${{ github.sha }}" \
+          "docker://${REGISTRY_DOCKERHUB_REPOSITORY_PATH}:${{ github.ref_name }}"
         skopeo copy --all \
-          "docker://${DOCKERHUB_REPOSITORY}:${{ github.ref_name }}" \
-          "docker://${DOCKERHUB_REPOSITORY}:latest"
+          "docker://${REGISTRY_DOCKERHUB_REPOSITORY_PATH}:${{ github.ref_name }}" \
+          "docker://${REGISTRY_DOCKERHUB_REPOSITORY_PATH}:latest"
 
   publish-dockerhub-readme:
     needs:
@@ -310,9 +310,9 @@ jobs:
     - name: Update image README and description
       uses: peter-evans/dockerhub-description@v2
       with:
-        username: ${{ vars.DOCKERHUB_USERNAME }}
-        password: ${{ secrets.DOCKERHUB_TOKEN }}
-        repository: ${{ env.DOCKERHUB_REPOSITORY }}
+        username: ${{ vars.REGISTRY_DOCKERHUB_PUSH_USERNAME }}
+        password: ${{ secrets.REGISTRY_DOCKERHUB_PUSH_TOKEN }}
+        repository: ${{ env.REGISTRY_DOCKERHUB_REPOSITORY_PATH }}
         short-description: ${{ github.event.repository.description }}
 
   publish-github:
@@ -345,11 +345,11 @@ jobs:
     - name: Tags and push
       run: |
         skopeo copy --all \
-          "docker://ghcr.io/${{ env.GHCR_REPOSITORY }}${DOCKERFILE_NAME_SUFFIX}:${{ github.ref_name }}.${{ github.sha }}" \
-          "docker://ghcr.io/${{ env.GHCR_REPOSITORY }}${DOCKERFILE_NAME_SUFFIX}:${{ github.ref_name }}.${{ needs.configure.outputs.build_commit_short_sha }}"
+          "docker://ghcr.io/${{ env.REGISTRY_GHCR_REPOSITORY_PATH }}${DOCKERFILE_NAME_SUFFIX}:${{ github.ref_name }}.${{ github.sha }}" \
+          "docker://ghcr.io/${{ env.REGISTRY_GHCR_REPOSITORY_PATH }}${DOCKERFILE_NAME_SUFFIX}:${{ github.ref_name }}.${{ needs.configure.outputs.build_commit_short_sha }}"
         skopeo copy --all \
-          "docker://ghcr.io/${{ env.GHCR_REPOSITORY }}${DOCKERFILE_NAME_SUFFIX}:${{ github.ref_name }}.${{ needs.configure.outputs.build_commit_short_sha }}" \
-          "docker://ghcr.io/${{ env.GHCR_REPOSITORY }}${DOCKERFILE_NAME_SUFFIX}:${{ github.ref_name }}"
+          "docker://ghcr.io/${{ env.REGISTRY_GHCR_REPOSITORY_PATH }}${DOCKERFILE_NAME_SUFFIX}:${{ github.ref_name }}.${{ needs.configure.outputs.build_commit_short_sha }}" \
+          "docker://ghcr.io/${{ env.REGISTRY_GHCR_REPOSITORY_PATH }}${DOCKERFILE_NAME_SUFFIX}:${{ github.ref_name }}"
         skopeo copy --all \
-          "docker://ghcr.io/${{ env.GHCR_REPOSITORY }}${DOCKERFILE_NAME_SUFFIX}:${{ github.ref_name }}" \
-          "docker://ghcr.io/${{ env.GHCR_REPOSITORY }}${DOCKERFILE_NAME_SUFFIX}:latest"
+          "docker://ghcr.io/${{ env.REGISTRY_GHCR_REPOSITORY_PATH }}${DOCKERFILE_NAME_SUFFIX}:${{ github.ref_name }}" \
+          "docker://ghcr.io/${{ env.REGISTRY_GHCR_REPOSITORY_PATH }}${DOCKERFILE_NAME_SUFFIX}:latest"
